---

- name: Evaluate if 'sapsys' group already exists
  shell: >
    set -o pipefail && grep sapsys /etc/group | cut -d ":" -f 3
  register: __sap_hana_deployment_register_checkgroup
  changed_when: false
  ignore_errors: true

- name: Get next available group ID in the 1000-1100 range
  shell: >
    awk -F: '{ uid[$3]=1 }END{ for(x=1000; x<=1100; x++) { if(uid[x] != ""){}else{print x; exit; }}}' /etc/group
  register: __sap_hana_deployment_register_nextgroupid
  when: __sap_hana_deployment_register_checkgroup.stdout | length == 0

- name: Set fact for group ID if 'sapsys' group does not exist
  set_fact:
    sap_hana_deployment_hana_groupid: "{{ __sap_hana_deployment_register_nextgroupid.stdout }}"
  when: __sap_hana_deployment_register_checkgroup.stdout | length == 0

- name: Set fact for group ID if 'sapsys' group exists
  set_fact:
    sap_hana_deployment_hana_groupid: "{{ __sap_hana_deployment_register_checkgroup.stdout }}"
  when: __sap_hana_deployment_register_checkgroup.stdout | length > 0
