---

- name: Get next available user ID in the 1000-1100 range
  shell: >
    awk -F: '{ uid[$3]=1 }END{ for(x=1000; x<=1100; x++) { if(uid[x] != ""){}else{ print x; exit; }}}' /etc/passwd
  register: __sap_hana_deployment_register_nextuserid
  changed_when: false
  failed_when: __sap_hana_deployment_register_nextuserid is failed

- name: Set fact for user ID
  set_fact:
    sap_hana_deployment_hana_userid: "{{ __sap_hana_deployment_register_nextuserid.stdout }}"
