---

- name: Set permissions of installation directories
  file:
    path: "{{ line_item.name }}"
    state: directory
    mode: "{{ line_item.value }}"
  with_items: "{{ sap_hana_deployment_directories_permissions }}"
  loop_control:
    loop_var: line_item
  when: sap_hana_deployment_set_permissions

- name: Assert correct permissions of installation directories
  include_tasks: directories-permissions-assert-loop-block.yml
  loop: "{{ sap_hana_deployment_directories_permissions }}"
  loop_control:
    loop_var: line_item
  when: not sap_hana_deployment_set_permissions

- name: Determine SAP HANA bundle file type
  set_fact:
    __sap_hana_preconfigure_fact_hana_bundle_file_type: '{{ sap_hana_deployment_bundle_file_name.split(".")[-1] }}'
  when: (( sap_hana_installdir is none ) or ( sap_hana_installdir | trim == ''))

- name: Show SAP HANA bundle file type
  debug:
    var: __sap_hana_preconfigure_fact_hana_bundle_file_type
  when: (( sap_hana_installdir is none ) or ( sap_hana_installdir | trim == ''))

- name: Copy the necessary SAP files from the control node
  block:
    - name: Copy the SAP HANA installation bundle file from the control node
      copy:
        src: "{{ sap_hana_deployment_bundle_path_cn }}/{{ sap_hana_deployment_bundle_file_name }}"
        dest: "{{ sap_hana_deployment_bundle_path_mn }}/"

    - name: In case the SAP HANA bundle file is a SAR file, copy SAPCAR and set permissions to '0755'
      copy:
        src: "{{ sap_hana_deployment_sapcar_path_cn }}/{{ sap_hana_deployment_sapcar_file_name }}"
        dest: "{{ sap_hana_deployment_sapcar_path_mn }}/"
        mode: '0755'
      when: __sap_hana_preconfigure_fact_hana_bundle_file_type == "SAR"

  when:
    - sap_hana_deployment_bundle_is_on_control_node
    - not sap_hana_deployment_bundle_is_on_managed_node

- name: Copy the necessary SAP files from a third node
  block:
    - name: Get the remote user
      set_fact:
        __sap_hana_deployment_fact_remote_user: "{{ lookup('env', 'USER') }}"

    - name: Copy the SAP HANA installation bundle file from a third node
      command: scp -p {{ sap_hana_deployment_sap_software_remote_location }}/{{ sap_hana_deployment_bundle_file_name }} \
        {{ __sap_hana_deployment_fact_remote_user }}@{{ inventory_hostname }}:{{ sap_hana_deployment_bundle_path_mn }}/
      delegate_to: localhost

    - name: In case the SAP HANA bundle file is a SAR file, copy SAPCAR
      command: scp -p {{ sap_hana_deployment_sap_software_remote_location }}/{{ sap_hana_deployment_sapcar_file_name }} \
        {{ __sap_hana_deployment_fact_remote_user }}@{{ inventory_hostname }}:{{ sap_hana_deployment_sapcar_path_mn }}/
      delegate_to: localhost
      when: __sap_hana_preconfigure_fact_hana_bundle_file_type == "SAR"

    - name: In case the SAP HANA bundle file is a SAR file, set the permission of SAPCAR to '0755'
      file:
        path: "{{ sap_hana_deployment_sapcar_path_mn }}/{{ sap_hana_deployment_sapcar_file_name }}"
        mode: '0755'
      when: __sap_hana_preconfigure_fact_hana_bundle_file_type == "SAR"

  when:
    - not sap_hana_deployment_bundle_is_on_control_node
    - not sap_hana_deployment_bundle_is_on_managed_node
    - (( sap_hana_installdir is none ) or ( sap_hana_installdir | trim == ''))

- name: Extract the SAP HANA SAPCAR archive
  block:
    - name: Use SAPCAR to extract the SAP HANA bundle SAR file
      command: >-
        {{ sap_hana_deployment_sapcar_path_mn }}/{{ sap_hana_deployment_sapcar_file_name }}
        -xvf {{ sap_hana_deployment_bundle_path_mn }}/{{ sap_hana_deployment_bundle_file_name }}
        -manifest SIGNATURE.SMF
      register: sap_hana_deployment_register_extractbundle
      args:
        chdir: "{{ sap_hana_deployment_hana_extract_path }}"
      changed_when: "'SAPCAR: processing archive' in sap_hana_deployment_register_extractbundle.stdout"

    - name: Set fact for the SAP HANA installer path
      set_fact:
        sap_hana_installdir: "{{ sap_hana_deployment_hana_extract_path }}/SAP_HANA_DATABASE"
  when:
    - not(( sap_hana_deployment_bundle_path_mn is none ) or ( sap_hana_deployment_bundle_path_mn | trim == ''))
    - not(( sap_hana_deployment_bundle_file_name is none ) or (sap_hana_deployment_bundle_file_name | trim == ''))
    - __sap_hana_preconfigure_fact_hana_bundle_file_type == "SAR"

- name: Extract the SAP HANA ZIP archive
  block:
    - name: Unzip the SAP HANA bundle ZIP file
      unarchive:
        src: "{{ sap_hana_deployment_bundle_path_mn }}/{{ sap_hana_deployment_bundle_file_name }}"
        dest: "{{ sap_hana_deployment_hana_extract_path }}"
        remote_src: yes
        mode: '0755'
      register: sap_hana_deployment_register_extractzip

    - name: Set fact for the SAP HANA installer path
      set_fact:
        sap_hana_installdir: "{{ sap_hana_deployment_hana_extract_path }}/DATA_UNITS/HDB_SERVER_LINUX_{{ ansible_architecture|upper }}"
  when:
    - not(( sap_hana_deployment_bundle_path_mn is none ) or ( sap_hana_deployment_bundle_path_mn | trim == ''))
    - not(( sap_hana_deployment_bundle_file_name is none ) or (sap_hana_deployment_bundle_file_name | trim == ''))
    - __sap_hana_preconfigure_fact_hana_bundle_file_type == "ZIP"

- name: Check if file 'hdblcm' is in {{ sap_hana_installdir }}
  stat:
    path: "{{ sap_hana_installdir + '/hdblcm' }}"
  register: sap_hana_deployment_register_hdblcm_stat
  failed_when: not sap_hana_deployment_register_hdblcm_stat.stat.exists

- name: Create temporary directory to store the processed template
  tempfile:
    state: directory
    suffix: hanaconfig
  register: tmpdir

- name: "Process HANA Configfile Template"
  template:
    src: "{{ role_path }}/templates/configfile.j2"
    dest: "{{ tmpdir.path }}/configfile.cfg"
    mode: '0644'
  register: cftemplate

- name: Copy file tail-f-hdblcm-trc.sh to "{{ tmpdir.path }}"
  copy:
    src: tmp/tail-f-hdblcm-trc.sh
    dest: "{{ tmpdir.path }}/tail-f-hdblcm-trc.sh"
    owner: root
    group: root
    mode: '0755'

- name: Show how to watch the installation process in real time
  debug:
    msg:
      - 'Once the task "Install SAP HANA" has started, you can use the following command
         in a terminal session on the managed node to watch the installation progress in real time:'
      - "{{ tmpdir.path }}/tail-f-hdblcm-trc.sh"
      - 'Alternatively, you can run the following command on the control node:'
      - "ssh {{ inventory_hostname }} {{ tmpdir.path }}/tail-f-hdblcm-trc.sh"

- name: Install SAP HANA
  command: "./hdblcm {{ sap_hana_deployment_hdblcm_extraargs }} --configfile={{ tmpdir.path }}/configfile.cfg -b"
  register: installhana
  args:
    chdir: "{{ sap_hana_installdir }}"
  changed_when: "'SAP HANA Lifecycle Management' in installhana.stdout"
