---

- name: Set permissions of installation directories to 0755
  file:
    path: "{{ line_item }}"
    state: directory
    mode: 0755
  loop:
    - /hana/shared
    - /hana/data
    - /hana/log
    - /usr/sap
  loop_control:
    loop_var: line_item
  when: sap_hana_deployment_set_permissions

- name: Assert correct permissions of installation directories
  block:
  - name: Get permissions of /hana/shared
    stat:
      path: /hana/shared
    register: __sap_hana_deployment_register_stat_hana_shared

  - name: Assert that permissions for /hana/shared are correct
    assert:
      that: __sap_hana_deployment_register_stat_hana_shared.stat.mode == '0755'
      fail_msg: "FAIL: /hana/shared has permissions {{ __sap_hana_deployment_register_stat_hana_shared.stat.mode }} but needs to have '0755'!"
      success_msg: "PASS: /hana/shared has correct permissions: {{ __sap_hana_deployment_register_stat_hana_shared.stat.mode }}."

  - name: Get permissions of /hana/data
    stat:
      path: /hana/shared
    register: __sap_hana_deployment_register_stat_hana_data

  - name: Assert that permissions for /hana/data are correct
    assert:
      that: __sap_hana_deployment_register_stat_hana_data.stat.mode == '0755'
      fail_msg: "FAIL: /hana/data has permissions {{ __sap_hana_deployment_register_stat_hana_data.stat.mode }} but needs to have '0755'!"
      success_msg: "PASS: /hana/data has correct permissions: {{ __sap_hana_deployment_register_stat_hana_data.stat.mode }}."

  - name: Get permissions of /hana/log
    stat:
      path: /hana/log
    register: __sap_hana_deployment_register_stat_hana_log

  - name: Assert that permissions for /hana/log are correct
    assert:
      that: __sap_hana_deployment_register_stat_hana_log.stat.mode == '0755'
      fail_msg: "FAIL: /hana/log has permissions {{ __sap_hana_deployment_register_stat_hana_log.stat.mode }} but needs to have '0755'!"
      success_msg: "PASS: /hana/log has correct permissions: {{ __sap_hana_deployment_register_stat_hana_log.stat.mode }}."

  - name: Get permissions of /usr/sap
    stat:
      path: /usr/sap
    register: __sap_hana_deployment_register_stat_usr_sap

  - name: Assert that permissions for /usr/sap are correct
    assert:
      that: __sap_hana_deployment_register_stat_usr_sap.stat.mode == '0755'
      fail_msg: "FAIL: /usr/sap has permissions {{ __sap_hana_deployment_register_stat_usr_sap.stat.mode }} but needs to have '0755'!"
      success_msg: "PASS: /usr/sap has correct permissions: {{ __sap_hana_deployment_register_stat_usr_sap.stat.mode }}."

  when: not sap_hana_deployment_set_permissions

- name: Unpack SAPCAR archive (backwards compatibility)
  block:
    - name: Use SAPCAR to extract the SAP HANA Bundle SAR file
      command: >-
        {{ sap_hana_deployment_sapcar_path }}/{{ sap_hana_deployment_sapcar_file_name }} \
        -xvf {{ sap_hana_deployment_bundle_path }}/{{ sap_hana_deployment_bundle_sar_file_name }} \
        -manifest SIGNATURE.SMF
      register: sap_hana_deployment_register_extractbundle
      args:
        chdir: "{{ sap_hana_deployment_sapcar_path }}"
      changed_when: "'SAPCAR: processing archive' in sap_hana_deployment_register_extractbundle.stdout"

    - name: Setting fact for HANA installer path
      set_fact:
        sap_hana_installdir: "{{ sap_hana_deployment_sapcar_path }}/SAP_HANA_DATABASE"
  when:
    - not(( sap_hana_deployment_bundle_path is none ) or ( sap_hana_deployment_bundle_path | trim == ''))
    - not(( sap_hana_deployment_bundle_sar_file_name is none ) or (sap_hana_deployment_bundle_sar_file_name | trim == ''))

- name: Extract ZIP archive
  block:
    - name: Use unarchive to extract the SAP HANA Bundle ZIP file
      unarchive:
        src: "{{ sap_hana_deployment_zip_path }}/{{ sap_hana_deployment_zip_file_name }}"
        dest: "{{ sap_hana_deployment_zip_path }}"
      register: sap_hana_deployment_register_extractzip

    - name: Setting fact for HANA installer path
      set_fact:
        sap_hana_installdir: "{{ sap_hana_deployment_zip_path }}/DATA_UNITS/HDB_SERVER_LINUX_X86_64"
  when:
    - not(( sap_hana_deployment_zip_path is none ) or ( sap_hana_deployment_zip_path | trim == ''))
    - not(( sap_hana_deployment_zip_file_name is none ) or (sap_hana_deployment_zip_file_name | trim == ''))

- name: Check availability of "{{ sap_hana_installdir + '/hdblcm' }}"
  stat:
    path: "{{ sap_hana_installdir + '/hdblcm' }}"
  register: sap_hana_deployment_register_hdblcm_stat
  failed_when: not sap_hana_deployment_register_hdblcm_stat.stat.exists

- name: Create temporary directory to store the processed template
  tempfile:
    state: directory
    suffix: hanaconfig
  register: tmpdir

- name: "Process HANA Configfile Template"
  template:
    src: "{{ role_path }}/templates/configfile.j2"
    dest: "{{ tmpdir.path }}/configfile.cfg"
  register: cftemplate

- name: Copy file /tmp/tail-f-hdblcm-trc.sh
  copy:
    src: tmp/tail-f-hdblcm-trc.sh
    dest: /tmp/tail-f-hdblcm-trc.sh
    owner: root
    group: root
    mode: '0755'

- name: Show how to watch the installation process in real time
  debug:
    msg:
      - 'Once the task "Install SAP HANA" has started, you can use the following command in
         in another terminal to watch the installation progress in real time:'
      - ssh {{ inventory_hostname }} /tmp/tail-f-hdblcm-trc.sh

- name: Install SAP HANA
  command: "./hdblcm {{ sap_hana_deployment_hdblcm_extraargs }} --configfile={{ tmpdir.path }}/configfile.cfg -b"
  register: installhana
  args:
    chdir: "{{ sap_hana_installdir }}"
  changed_when: "'SAP HANA Lifecycle Management' in installhana.stdout"
