---

- name: Check if file 'hdblcm' is in the SAP HANA installation directory
  stat:
    path: "{{ sap_hana_installdir + '/hdblcm' }}"
  register: __sap_hana_deployment_register_hdblcm_stat
  failed_when: not __sap_hana_deployment_register_hdblcm_stat.stat.exists
  when: sap_hana_deployment_install_primary|d(true)

- name: Create temporary directory to store the processed template
  tempfile:
    state: directory
    suffix: hanaconfig
  register: __sap_hana_deployment_register_tmpdir

- name: Process HANA configfile template
  template:
    src: "{{ role_path }}/templates/configfile.j2"
    dest: "{{ __sap_hana_deployment_register_tmpdir.path }}/configfile.cfg"
    mode: '0644'
  register: __sap_hana_deployment_register_cftemplate

- name: Install SAP HANA
  block:

    - name: Copy file tail-f-hdblcm-install-trc.sh to '{{ __sap_hana_deployment_register_tmpdir.path }}'
      copy:
        src: tmp/tail-f-hdblcm-install-trc.sh
        dest: "{{ __sap_hana_deployment_register_tmpdir.path }}/tail-f-hdblcm-install-trc.sh"
        owner: root
        group: root
        mode: '0755'

    - name: Show how to watch the install process in real time
      debug:
        msg:
          - 'Once the task "Perform the SAP HANA installation" has started, you can use the following command'
          - 'in a terminal session on the managed node to watch the install progress in real time:'
          - "{{ __sap_hana_deployment_register_tmpdir.path }}/tail-f-hdblcm-install-trc.sh"
          - 'Alternatively, you can run the following command on the control node:'
          - "ssh {{ inventory_hostname }} {{ __sap_hana_deployment_register_tmpdir.path }}/tail-f-hdblcm-install-trc.sh"

    - name: Perform the SAP HANA installation
      command: "./hdblcm {{ sap_hana_deployment_hdblcm_extraargs }}
                --configfile={{ __sap_hana_deployment_register_tmpdir.path }}/configfile.cfg
                -b"
      register: __sap_hana_deployment_register_hdblcm_install
      args:
        chdir: "{{ sap_hana_installdir }}"
      changed_when: "'SAP HANA Lifecycle Management' in __sap_hana_deployment_register_hdblcm_install.stdout"

  when: sap_hana_deployment_install_primary|d(true)

- name: Add hosts to the existing SAP HANA installation
  command: "./hdblcm {{ sap_hana_deployment_hdblcm_extraargs }}
            --action=add_hosts
            --addhosts={{ sap_hana_deployment_addhosts }}
            --password={{ sap_hana_deployment_sidadm_password }}
            --configfile={{ __sap_hana_deployment_register_tmpdir.path }}/configfile.cfg
            -b"
  register: __sap_hana_deployment_register_hdblcm_add_hosts
  args:
    chdir: "{{ sap_hana_deployment_hana_install_path }}/{{ sap_hana_deployment_hana_sid }}/hdblcm"
  changed_when: "'SAP HANA Lifecycle Management' in __sap_hana_deployment_register_hdblcm_add_hosts.stdout"
  when: not sap_hana_deployment_install_primary|d(true)

- name: Show the result of hdblcm add_hosts
  debug:
    var: __sap_hana_deployment_register_hdblcm_add_hosts.stdout
  when: not sap_hana_deployment_install_primary|d(true)
