---

- name: Check if file 'hdblcm' is in {{ sap_hana_installdir }}
  stat:
    path: "{{ sap_hana_installdir + '/hdblcm' }}"
  register: sap_hana_deployment_register_hdblcm_stat
  failed_when: not sap_hana_deployment_register_hdblcm_stat.stat.exists

- name: Create temporary directory to store the processed template
  tempfile:
    state: directory
    suffix: hanaconfig
  register: tmpdir

- name: "Process HANA Configfile Template"
  template:
    src: "{{ role_path }}/templates/configfile.j2"
    dest: "{{ tmpdir.path }}/configfile.cfg"
    mode: '0644'
  register: cftemplate

- name: Copy file tail-f-hdblcm-trc.sh to "{{ tmpdir.path }}"
  copy:
    src: tmp/tail-f-hdblcm-trc.sh
    dest: "{{ tmpdir.path }}/tail-f-hdblcm-trc.sh"
    owner: root
    group: root
    mode: '0755'

- name: Show how to watch the installation process in real time
  debug:
    msg:
      - 'Once the task "Install SAP HANA" has started, you can use the following command'
      - 'in a terminal session on the managed node to watch the installation progress in real time:'
      - "{{ tmpdir.path }}/tail-f-hdblcm-trc.sh"
      - 'Alternatively, you can run the following command on the control node:'
      - "ssh {{ inventory_hostname }} {{ tmpdir.path }}/tail-f-hdblcm-trc.sh"

- name: Install SAP HANA
  command: "./hdblcm {{ sap_hana_deployment_hdblcm_extraargs }} --configfile={{ tmpdir.path }}/configfile.cfg -b"
  register: installhana
  args:
    chdir: "{{ sap_hana_installdir }}"
  changed_when: "'SAP HANA Lifecycle Management' in installhana.stdout"
