---

- import_tasks: ev_user.yml
  when:
    - sap_hana_deployment_hana_userid == ''
    - not sap_hana_deployment_apply_license

- import_tasks: ev_group.yml
  when:
    - sap_hana_deployment_hana_groupid == ''
    - not sap_hana_deployment_apply_license

- import_tasks: password_facts.yml
  when: sap_hana_deployment_use_master_password == 'y'

- import_tasks: set_or_verify_permissions.yml

- import_tasks: provide_hana_installation_bundle.yml
  when: (( sap_hana_installdir is none ) or ( sap_hana_installdir | trim == ''))

- import_tasks: install_hana.yml

- import_tasks: apply_hana_license.yml
  when: sap_hana_deployment_apply_license
